#!/bin/sh
set -o xtrace

CPPNETLIB=cpp-netlib-0.11.1-final
YARA=yara-3.2.0

# go to libs
cd $1 && [ -e prepare_Linux ] && [ ! -e prepared ] && \

cd src/civetweb && \
make lib WITH_CPP=1 && \
cd ../../ && \

cd src && \
tar xvfz ${CPPNETLIB}.tar.gz && \
cd ${CPPNETLIB} && \
cmake CMakeLists.txt && \
make cppnetlib-uri && \
cd ../../ && \

cd src && \
tar xvfz ${YARA}.tar.gz && \
cd ${YARA} && \
sh build.sh && \
cd ../../ && \

ln -s -f src/cef_binary_3.2217.1940_macosx64 cef_current && \
ln -s -f src/${CPPNETLIB}/libs/network/src/libcppnetlib-uri.a libcppnetlib-uri.a && \
ln -s -f src/civetweb/libcivetweb.a libcivetweb.a && \
ln -s -f src/${YARA}/libyara/.libs/libyara.a libyara.a && \

ln -s -f src/${YARA}/libyara/include yara_include && \
ln -s -f src/${CPPNETLIB}/ netlib_include && \
ln -s -f src/civetweb/include civetweb_include && \

touch prepared

# echo "deb http://llvm.org/apt/wheezy/ llvm-toolchain-wheezy main"> /etc/apt/sources.list.d/llvm.list
# apt-get update
# apt-get install lldb-3.4 lldb-3.4-dev libclang-3.4-dev libc++-dev autoconf libtool
# liblldb-3.5-dev clang-3.5-dev llvm-3.5-dev
# sudo update-alternatives --config c++
