#!/bin/sh
set -o xtrace

# go to libs
cd $1 && [ -e prepare_Linux ] && [ ! -e prepared ] && \

cd src/civetweb && \
make lib WITH_CPP=1 && \
cd ../../ && \

cd src/cpp-netlib-0.11.0-final && \
cmake CMakeLists.txt && \
make cppnetlib-uri && \
cd ../../ && \

cd src && \
tar xvfz yara-3.2.0.tar.gz && \
cd yara-3.2.0 && \
sh build.sh && \
cd ../../ && \

ln -s src/cef_binary_3.2217.1940_macosx64 cef_current && \
ln -s src/cpp-netlib-0.11.0-final/libs/network/src/libcppnetlib-uri.a libcppnetlib-uri.a && \
ln -s src/civetweb/libcivetweb.a libcivetweb.a && \
ln -s src/yara-3.2.0/libyara/.libs/libyara.a libyara.a && \

ln -s src/yara-3.2.0/libyara/include yara_include && \
ln -s src/cpp-netlib-0.11.0-final/ netlib_include && \
ln -s src/civetweb/include civetweb_include && \

touch prepared

# echo "deb http://llvm.org/apt/wheezy/ llvm-toolchain-wheezy main"> /etc/apt/sources.list.d/llvm.list
# apt-get update
# apt-get install lldb-3.4 lldb-3.4-dev libclang-3.4-dev libc++-dev
# sudo update-alternatives --config c++
