#!/bin/sh
set -o xtrace

# go to libs
cd $1 && [ -e prepare_Darwin ] && [ ! -e prepared ] && \

cd src/civetweb && \
make lib WITH_CPP=1 && \
cd ../../ && \

cd src/cpp-netlib-0.11.1-final && \
cmake CMakeLists.txt && \
make cppnetlib-uri && \
cd ../../ && \

cd src && \
tar xvfz yara-3.2.0.tar.gz && \
cd yara-3.2.0 && \
./bootstrap.sh && \
./configure && \
make && \
cd ../../ && \

ln -i -s src/cef_binary_3.2217.1940_macosx64 cef_current && \

ln -i -s src/cpp-netlib-0.11.1-final/libs/network/src/libcppnetlib-uri.a libcppnetlib-uri.a && \
ln -i -s src/civetweb/libcivetweb.a libcivetweb.a && \
ln -i -s src/yara-3.2.0/libyara/.libs/libyara.a libyara.a && \

ln -i -s /usr/local/lib/libboost_log-mt.a libboost_log-mt.a && \
ln -i -s /usr/local/lib/libboost_filesystem-mt.a libboost_filesystem-mt.a && \
ln -i -s /usr/local/lib/libboost_system-mt.a libboost_system-mt.a && \
ln -i -s /usr/local/lib/libboost_thread-mt.a libboost_thread-mt.a && \
ln -i -s /usr/local/lib/libboost_regex.a libboost_regex.a && \

ln -i -s src/gtest.framework gtest.framework && \
ln -i -s src/LLDB.framework LLDB.framework && \

ln -i -s src/lldb_headers lldb_include && \
ln -i -s src/yara-3.2.0/libyara/include yara_include && \
ln -i -s src/cpp-netlib-0.11.1-final/ netlib_include && \
ln -i -s src/civetweb/include civetweb_include && \

touch prepared